### PR TITLE
cache files in -CacheDir in the router mode

### PR DESCRIPTION
**Pull request by fancy-rabbit**
when goproxy is in the router mode, cache the files retrieved from proxyHost in downloadRoot.
as in the proxy mode, .list files will be cached for only 5 minutes.

as mentioned in #88

### CODE REVIEW

**Comment by fancy-rabbit** [comment]
cc @imneov

**Comment by imneov** [comment]
When we need use private repo,  the repo is in the develop usually.

The cache of repo without version is clean hardly, so we don't suggest cache it.

**Comment by fancy-rabbit** [comment]
@imneov this PR is about to cache the packages of the public repositories, not to cache private ones.

meanwhile, the private ones went through rt.srv.ServeHTTP() by the excludeHost directive, which will be cached indeed.....

**Comment by fancy-rabbit** [comment]
sounds more reasonable if we switch the [direct] ones of the proxy router to a plain NewSingleHostReverseProxy() instead.
because A 'router' does not need to cache anything. but a 'proxy' needs to, so in the proxy mode, the current behavior could left unchanged.

**Comment by imneov** [comment]
Yes, it's my fault. This is a bug, the right behavior is cache the proxy repo (public) and don't cache the router repo (private).

**Comment by oiooj** [comment]
cc @ianwoolf

**Comment by fancy-rabbit** [comment]
@imneov @oiooj emm, I'll submit a new PR for re-using the cache logic for the public repos but route to private ones via a plain httputil.NewSingleHostReverseProxy() instead.
closing this.

**Comment by fancy-rabbit** [comment]
seems I've made a mistake. I'll reopen this PR with some minor fixes.

As of go1.13, GOPRIVATE(or GONOPROXY/GONOSUMDB for finer controlling) should be set if the path to some go modules are private, it automatically bypasses GOPROXY.
when using go<1.13(typically 1.12.9, the latest stable release), the current implementation of router mode could lead to unwanted cache in the router's -cacheDir.

As @imneov said when the private modules are under development, it could be hard to clean the cache, but pseudo-versions can be taken in place if semver tags didn't exist. go get private.domain/path/to/pkg@7ca32eb868bf will put something like v0.0.0-20180910000450-7ca32eb868bf(just like golang.org/x/crypto, it doesn't have any release tags). commit hashes will not be duplicated even if you force-pushed to a private repository, huh?
And also, the TTL of .list files (5min) will not affect specifying commit hashes.

**Comment by ianwoolf** [comment]
LGTM

**Comment by oiooj** [comment]
LGTM Thanks @fancy-rabbit

**Comment by fancy-rabbit** [comment]
@oiooj may I get a t-shirt? I sent an email for inquiry but receive no response- -

**Comment by oiooj** [comment]
@fancy-rabbit Sure, Thanks for your work.

**Pull request merged**
