### PR TITLE
fix file mode 

### PR DESCRIPTION
**Pull request by formych**
755 => os.ModePerm

### CODE REVIEW

**Comment by jsign** [comment]
Just in case: 755 and `os.ModePerm` [aren't equivalent](https://github.com/golang/go/blob/master/src/os/types.go#L62).

**Comment by formych** [comment]
> Just in case: 755 and `os.ModePerm` [aren't equivalent](https://github.com/golang/go/blob/master/src/os/types.go#L62).

the result is 0755，try it ʘᴗʘ

**Comment by formych** [comment]
> Just in case: 755 and `os.ModePerm` [aren't equivalent](https://github.com/golang/go/blob/master/src/os/types.go#L62).

In progrom 755 is decimal digits, 0755 is octal, os.ModePerm  - unmask is  the result!

**Comment by formych** [comment]
> I think this change is not quite right, but I'll let @ianwoolf review this.
> 
> > ModePerm FileMode = 0777

If you do this,
http://127.0.0.1:8081/github.com/goproxyio/goproxy/@v/list, you will get this error, 
`open github.com/goproxyio/goproxy/@v/listproxy: permission denied`

ls  -al  in root dir, get this 
dr----x--x   2 renruifeng  staff    64  9 12 08:37 github.com


Here is an case , 755 vs 0755 in program not in chmod

https://digitalfortress.tech/php/difference-file-mode-0777-vs-777/?nsukey=IyAHxSfBpqHgLvX2Sr1RpfLa4vhHc39pYELaacWcs1wqzu%2FtT8vMIatDqT5w396X5ZyZPDXRhp5pBN8Xc9LCA0e5rfm1wEhuVFm6dqM19uab%2BohvIf%2B5iai9DSzwryKTde%2BYIiJ%2F0%2BVeoiSylOTtl7qgw2yK0d3eQF1ubYeF8XxtSuZf3b5%2BIq0GlwYS6zDLtKzBw2FXbWbFHokpg41gnw%3D%3D

0777 - 0022(unix unmask) = 0755

**Comment by ianwoolf** [comment]
agree @jsign. 
I don't get the reason for this change.

**Comment by ianwoolf** [comment]
LGTM

**Pull request merged**
