### PR TITLE
remove repeated signal

### PR DESCRIPTION
**Pull request by formych**
remove repeated sigterm signal

### CODE REVIEW

**Comment by oiooj** [comment]
LGTM, Thanks @formych

**Comment by formych** [comment]
> LGTM, Thanks @formych

Can i get a T-Shirt? I like it very much!

**Comment by oiooj** [comment]
Sure, you will get a email later. Thanks again.

**Comment by formych** [comment]
> Sure, you will get a email later. Thanks again.

谢谢老哥，下次一定提一个有质量的pr, ^_^

**Pull request merged**
